help_text: |
  1) wiki - find some title in wikipedia
  using: w [or W, в, В] <some_name>
  example: "w go"

  2) newton - powerful math calculator
  using: n [or N, н, Н] <operation> <expression>
  example: "n derive x^2+2x"
  list of available operations:
    simplify
    factor
    derive
    integrate
    zeroes
    tangent
    area
    cos
    sin
    tan
    arccos
    arcsin
    arctan
    abs
    log

  3) playground - write and run go program
  using: p [or P, п, П] <code>
  example: p package main

             import (
               "fmt"
             )

             func main() {
               fmt.Println("Hello, World!")
             }

  4) golang - tips and tricks
  using: go [or Go, го, Го] <tag1> <tag2> ...
  example: go extract prefix

wiki:
  tag: wiki
  url: https://ru.wikipedia.org/w/api.php?format=json&action=query&prop=extracts&exintro=&explaintext=&titles=

newton:
  tag: newton
  url: https://newton.now.sh/api/v2/
  operations:
    - simplify
    - factor
    - derive
    - integrate
    - zeroes
    - tangent
    - area
    - cos
    - sin
    - tan
    - arccos
    - arcsin
    - arctan
    - abs
    - log

playground:
  tag: playground
  url: https://play.golang.org/compile

markov:
  tag: markov
  file: services/markov/platon.txt

golang:
  tag: golang
  file: databases/golang.db

# map of services; the service will be started if the message starts with one of the prefixes
services:
  wiki:
    - "w "
    - "W "
    - "wiki "
    - "Wiki "
    - "в "
    - "В "
    - "вики "
    - "Вики "
  newton:
    - "n "
    - "N "
    - "newton "
    - "Newton "
    - "н "
    - "Н "
    - "ньютон "
    - "Ньютон "
  playground:
    - "p "
    - "P "
    - "play "
    - "Play "
    - "п "
    - "П "
    - "плэй "
    - "Плэй "
#  markov:
#    - "m "
#    - "M "
#    - "markov "
#    - "Markov "
#    - "м "
#    - "М "
#    - "марков "
#    - "Марков "
  golang:
    - "go "
    - "Go "
    - "golang "
    - "Golang "
    - "го "
    - "Го "
    - "голанг "
    - "Голанг "
